### PR TITLE
Mult full array

### PR DESCRIPTION
**Pull request by wicked008**
The 4 cycle full array multiplier with all the improvements in the adder and shifter. Two implementations were tested and were functionally correct. Not all cache configs are tested though.

### CODE REVIEW

**Comment by fayalalebrun** [comment]
When you say tested two implementations, do you mean you also implemented radix_4?

**Comment by wicked008** [comment]
> When you say tested two implementations, do you mean you also implemented radix_4?

No, I meant I ran two synthesis and implementations with two cache configs to make sure changing the cache didn't have an effect on the behaviour. The radix-4 is unfortunately still broken but we do have an idea of how it would've performed compared with Full array multiplier.

**Comment by fayalalebrun** [comment]
It seems like there is duplicated code here already in master, like the shifter. Could you merge master into this before we merge it?

**Comment by wicked008** [comment]
> It seems like there is duplicated code here already in master, like the shifter. Could you merge master into this before we merge it?

Master was merged into this branch. Then the conflicts were resolved in commit [41ac9aa] and the new adder was added to the multiplier in the following commit.

**Comment by kr4b** [comment]
The merge commit is a bit messed up, but I don't think we need to care much about version control at this point, so I'm fine with it.

Besides some insignificant things, everything looks good. The multiplier is impressive.

**Pull request merged**
